package io.kestros.cms.archetype;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.Test;

/**
 * The archetypes resolve each other by a version hardcoded in archetype-post-generate.groovy, so
 * a set that is only partly bumped still builds and still passes every other test - it fails on an
 * end user's machine, when generate asks for an archetype version that was never published. That
 * has produced a green build twice.
 *
 * <p>These assertions do not care which version the repository is on. They care that the shipped
 * script, the five archetypes it generates from and the aggregator over them all say the same
 * thing.
 */
public class ArchetypeVersionConsistencyTest {

  private static final String SCRIPT = "/META-INF/archetype-post-generate.groovy";

  /** The four archetypes the post-generate script generates, in the order it generates them. */
  private static final String[] GENERATED_ARCHETYPES = {"kestros-api-archetype",
      "kestros-core-archetype", "kestros-content-archetype", "kestros-application-archetype"};

  /** The modules the aggregator builds - the four above plus the project archetype itself. */
  private static final String[] MODULES = {"kestros-api-archetype", "kestros-core-archetype",
      "kestros-content-archetype", "kestros-application-archetype", "kestros-project-archetype"};

  private static final String AGGREGATOR = "kestros-archetypes";

  /**
   * Surefire runs with the module directory as its working directory, so the sibling modules and
   * the aggregator are one level up.
   */
  private static final File REPOSITORY_ROOT = new File("..");

  private String script() throws IOException {
    final InputStream stream = getClass().getResourceAsStream(SCRIPT);
    assertTrue("archetype-post-generate.groovy is not on the classpath", stream != null);
    try (InputStream open = stream) {
      final java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream();
      final byte[] chunk = new byte[8192];
      int read;
      while ((read = open.read(chunk)) != -1) {
        buffer.write(chunk, 0, read);
      }
      return new String(buffer.toByteArray(), UTF_8);
    }
  }

  /**
   * The version each archetypeGenerate call asks for. The call passes the archetype name and then
   * its version as the next argument, which is the literal this looks for.
   */
  private Map<String, String> versionsRequestedByTheScript() throws IOException {
    final String source = script();
    final Map<String, String> requested = new LinkedHashMap<>();
    for (final String archetype : GENERATED_ARCHETYPES) {
      final Matcher matcher = Pattern.compile(
          "\"" + Pattern.quote(archetype) + "\"\\s*,\\s*'([^']+)'").matcher(source);
      assertTrue(archetype + " is not generated by archetype-post-generate.groovy",
          matcher.find());
      requested.put(archetype, matcher.group(1));
    }
    return requested;
  }

  /** The version a pom declares for itself - the one directly after its own artifactId. */
  private String declaredVersion(final File pom, final String artifactId) throws IOException {
    assertTrue(pom.getPath() + " does not exist", pom.isFile());
    final String source = new String(Files.readAllBytes(pom.toPath()), UTF_8);
    final Matcher matcher = Pattern.compile(
        "<artifactId>" + Pattern.quote(artifactId) + "</artifactId>\\s*<version>([^<]+)</version>")
        .matcher(source);
    assertTrue(pom.getPath() + " declares no version of its own for " + artifactId,
        matcher.find());
    return matcher.group(1);
  }

  private String declaredVersionOfModule(final String artifactId) throws IOException {
    return declaredVersion(new File(new File(REPOSITORY_ROOT, artifactId), "pom.xml"), artifactId);
  }

  @Test
  public void testEveryArchetypeTheScriptGeneratesAsksForTheSameVersion() throws Exception {
    final Set<String> distinct = new LinkedHashSet<>(versionsRequestedByTheScript().values());

    assertEquals("archetype-post-generate.groovy asks for a mixed set of versions: "
                 + versionsRequestedByTheScript(), 1, distinct.size());
  }

  @Test
  public void testTheScriptAsksForTheVersionEachArchetypeIsActuallyBuiltAt() throws Exception {
    for (final Map.Entry<String, String> requested : versionsRequestedByTheScript().entrySet()) {
      assertEquals(requested.getKey() + " is generated at a version it is not built at",
          declaredVersionOfModule(requested.getKey()), requested.getValue());
    }
  }

  @Test
  public void testEveryModuleInTheAggregatorIsAtTheSameVersion() throws Exception {
    final String projectArchetypeVersion = declaredVersionOfModule("kestros-project-archetype");

    for (final String module : MODULES) {
      assertEquals(module + " is not at the same version as the rest of the set",
          projectArchetypeVersion, declaredVersionOfModule(module));
    }
  }

  @Test
  public void testTheAggregatorIsAtTheSameVersionAsTheArchetypesItBuilds() throws Exception {
    // The aggregator is not published and the modules do not inherit from it - their parent block
    // is commented out - so nothing breaks at build time when it drifts. It is still the version
    // the repository is read as being on, and it was ruled on 2026-08-08 that it moves with them.
    assertEquals("the aggregator has drifted from the archetypes it builds",
        declaredVersionOfModule("kestros-project-archetype"),
        declaredVersion(new File(REPOSITORY_ROOT, "pom.xml"), AGGREGATOR));
  }
}
